### PR TITLE
New merged files

### PR DESCRIPTION
**Pull request by ttnnkkrr**
This one PR replaces previous PR and merges the new files and the UI updates

### CODE REVIEW

**Comment by ChessMess** [comment]
@makenziemoore @ttnnkkrr , On checkout page the final 'confirm' button appears to not trigger the secure submit javascript.

**Comment by ttnnkkrr** [comment]
i cannot duplicate

Might be a xampp thing?

**Comment by ttnnkkrr** [comment]
Nevermind that because its because bitnami deploy silently dies on the mail function. it just seems like the button didnt work
Editing the mail function solved the problem

**Review by ChessMess — APPROVED** [review]
Tested on clean install and plugin worked properly.

**Pull request merged**
